// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxdliyfphxbdkbvbonpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZGxpeWZwaHhiZGtidmJvbnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzM3NTksImV4cCI6MjA2ODk0OTc1OX0.GwYmJ5g1hTr9FuOnW1tWEYtb2JhAr_z8zTc0cmPfHsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});